### ISSUE TITLE
Add "redirect to page after login" feature 

### ISSUE THREAD

**Issue by jbuck** [jbuck/express-persona#2]
Requested by @brianloveswords.

Would this be something like "Always redirect to a certain page after logging in" or "Look at the query string for where to redirect"?

**Comment by ro-ka** [comment]
I would say both. You can specify a link where redirect to. When there is a link in the url it should use this and redirect to that link instead of the default.

**Comment by jbuck** [comment]
Going to close this issue, since you can override the [default verifyResponse](https://github.com/jbuck/express-persona#optional-options) to do what you want. Something to look at doing for the next minor version though!
