### ISSUE TITLE
ajax examples

### ISSUE THREAD

**Issue by ronnieoverby** [jbuck/express-persona#7]
For God's sakes use jQuery or some other modern javascript ajax library in your examples.

**Comment by jbuck** [comment]
I like writing code without dependencies, if I can. If you feel that strongly about it, please feel free to submit a patch and I'll merge it.

**Comment by ronnieoverby** [comment]
There's nothing wrong with depending on something that makes the
example code much easier to understand. Especially when that dependency is
something as ubiquitous as jQuery. The examples are for the benefit of
those who are taking a dependency on your module, not you.

By the way I do appreciate this project. Thank you.

**Comment by jbuck** [comment]
Going to close this issue since it hasn't seen any action in a few months. I will happily merge any any drive-by pull requests!
