### ISSUE TITLE
So this one is a pickle and a cow ..

### ISSUE THREAD

**Issue by operatorjen** [jbuck/express-persona#8]
If I have a separate authentication api (e.g. Facebook Connect) and they both piggy back on req.session.email and I'm not logged into Persona, it seems as though the session is reset for me even though I'm logged into the other one. 

What should I do, Jesus Baby Cow?

**Comment by jbuck** [comment]
You should set the `sessionKey` parameter: https://github.com/jbuck/express-persona#optional-options
